// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myproject.registration.web;

import com.myproject.registration.web.PersonBean;
import java.io.Serializable;

privileged aspect PersonBean_Roo_Serializable {
    
    declare parents: PersonBean implements Serializable;
    
    private static final long PersonBean.serialVersionUID = 1L;
    
}
